version: "2.2"
services:
  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: "${LETSENCRYPT_COMPANION_IMAGE}"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf.d:/etc/nginx/conf.d:rw
      - ./vhost.d:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html:rw
      - ./certs:/etc/nginx/certs:rw
    networks:
      - proxy_network
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-proxy-gen"
      NGINX_PROXY_CONTAINER: "nginx-proxy"


