version: "2.2"
services:
  graphscope:
    container_name: "${COMPOSE_PROJECT_NAME}-graphscope"
    image: "${GRAPHSCOPE}"
    restart: unless-stopped
    mem_limit: 2g
    mem_reservation: 2g
    environment:
      JAVA_OPTS: ""
      GS_CONFIGFILE: "config-${GRAPHSCOPE_CONFIGURATION}.yml"
    volumes:
      - ./graphscope-config:/opt/config
      - graphscope-logs:/opt/logs
      - graphscope-repository:/opt/repository
    networks:
      - metaphactory_network
    depends_on:
      - metaphactory
  metaphactory:
    volumes:
      - ./graphscope-apps/app-graphscope-${GRAPHSCOPE_CONFIGURATION}:/apps/app-graphscope-${GRAPHSCOPE_CONFIGURATION}
volumes:
  graphscope-logs:
  graphscope-repository:
