#!/usr/bin/env sh

sleep 15
apk update
apk add curl
curl -s 'http://graphdb:7200/rest/repositories' -X PUT -H 'Content-Type:application/json;charset=utf-8' --data '{"id":"default","params":{"queryTimeout":{"label":"Query time-out (seconds)","name":"queryTimeout","value":"0"},"inMemoryLiteralProperties":{"label":"Cache literal language tags","name":"inMemoryLiteralProperties","value":"true"},"nonInterpretablePredicates":{"label":"Non-interpretable predicates","name":"nonInterpretablePredicates","value":"http://www.w3.org/2000/01/rdf-schema#label;http://www.w3.org/1999/02/22-rdf-syntax-ns#type;http://www.ontotext.com/owlim/ces#gazetteerConfig;http://www.ontotext.com/owlim/ces#metadataConfig"},"ruleset":{"label":"Ruleset","name":"ruleset","value":"rdfsplus-optimized"},"readOnly":{"label":"Read-only","name":"readOnly","value":"false"},"title":{"label":"Repository title","name":"title","value":"GraphDB-Enterprise worker node"},"checkForInconsistencies":{"label":"Check for inconsistencies","name":"checkForInconsistencies","value":"false"},"disableSameAs":{"label":"Disable owl:sameAs","name":"disableSameAs","value":"true"},"enableLiteralIndex":{"label":"Enable literal index","name":"enableLiteralIndex","value":"true"},"entityIndexSize":{"label":"Entity index size","name":"entityIndexSize","value":"10000000"},"enableContextIndex":{"label":"Use context index","name":"enableContextIndex","value":"false"},"baseURL":{"label":"Base URL","name":"baseURL","value":"http://example.org/owlim#"},"queryLimitResults":{"label":"Limit query results","name":"queryLimitResults","value":"0"},"entityIdSize":{"label":"Entity ID bit-size","name":"entityIdSize","value":"32"},"throwQueryEvaluationExceptionOnTimeout":{"label":"Throw exception on query time-out","name":"throwQueryEvaluationExceptionOnTimeout","value":"false"},"id":{"label":"Repository ID","name":"id","value":"worker-test"},"storageFolder":{"label":"Storage folder","name":"storageFolder","value":"storage"},"enablePredicateList":{"label":"Use predicate indices","name":"enablePredicateList","value":"true"}},"title":"","type":"worker"}'
#curl -s -X POST -H 'Content-Type:text/turtle' -H 'Accept:text/csv' --data-binary "@/configs/exampleData.ttl" 'http://graphdb:7200/repositories/default/statements'
#curl -s -X POST -H 'Content-Type:application/sparql-update' --data-binary "@/configs/exampleLucene.erb" http://graphdb:7200/repositories/default/statements;
curl -s -X POST -H 'Content-Type:application/sparql-update' --data-binary "@/configs/enableautocomplete.sparql" http://graphdb:7200/repositories/default/statements;
